### ISSUE TITLE
chatbox not wider

### ISSUE THREAD

**Issue by SwissFred57** [adamlui/ai-web-extensions#18]
the chatbox is not wider no difference ON or OFF

**Comment by adamlui** [comment]
Hey @SwissFred57 it only takes effect if Widescreen Mode is also on

**Comment by adamlui** [comment]
@SwissFred57 it should be wider, are you using the extension? If not, what is your userscript manager? Also what is your browser and OS?

**Comment by SwissFred57** [comment]
i use windows 11 and Edge

![image](https://github.com/adamlui/chatgpt-apps/assets/123299068/b5778fc1-6345-48ca-8fbe-646a896ede03)

**Comment by adamlui** [comment]
@SwissFred57 I fixed it can you update @ https://gf.chatgptwidescreen.com or the About menu?
